name: Automated Data Preprocessing

on:
  push:
    paths:
      - 'namadataset_raw/**'
  workflow_dispatch:

jobs:
  run-preprocessing-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
        cache: 'pip'

    - name: Install Required Packages
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Execute Preprocessing Script
      run: |
        python preprocessing/automate_Zaky-Ramadhan.py

    - name: Commit and Push Processed Data
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add preprocessing/namadataset_preprocessing/data_bersih.csv
        git diff-index --quiet HEAD || (git commit -m "Umpan Balik Otomatis: Memperbarui data_bersih.csv via GitHub Actions" && git push)